import './globals.css'

export const metadata = {
  title: 'NextJS - Server fetch',
  description: 'Generated by create next app',
  author: 'jamj2000',
  keywords: ['nextjs', 'server fetch', 'error', 'loading']
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  )
}
